phrase:
  project_id: "908d4a07dcb5e3d507d2c0482a34970b"
  file_format: json
  push:
    sources:
    - file: ./locales/en.json
      params:
        locale_id: en
  pull:
    targets:
    - file: ./locales/en.json
      project_id: en
