phrase:
  project_id: "704089b8fd4c929aadbd38aa912439c9"
  file_format: react_simple_json
  push:
    targets:
    - file: ./locales/en.json
      params:
        locale_id: en
    - file: ./locales/pl.json
      params:
        locale_id: pl
    - file: ./locales/es.json
      params:
        locale_id: es
  pull:
    targets:
    - file: ./locales/en.json
      project_id: en
